/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.game_shelf;

import java.awt.event.WindowEvent;

/**
 *
 * @author GGulk
 */
public class UpdateFrame extends javax.swing.JFrame {

    //main menu we return to
    MainMenuInterface parent;
    //game were changing
    Game change;

    /**
     * Creates new form UpdateFrame
     *
     * @param c
     * @param p
     */
    public UpdateFrame(Game c, MainMenuInterface p) {
        initComponents();
        parent = p;
        change = c;
        
        if (c.getOwn()) {
            haveRadio.setSelected(true);
        } else {
            wantRadio.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        detailsCombo = new javax.swing.JComboBox<>();
        statusPane = new javax.swing.JPanel();
        haveRadio = new javax.swing.JRadioButton();
        wantRadio = new javax.swing.JRadioButton();
        detailsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(34, 39, 42));

        jPanel1.setBackground(new java.awt.Color(34, 39, 42));

        closeButton.setBackground(new java.awt.Color(75, 163, 81));
        closeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.setBorderPainted(false);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(75, 163, 81));
        confirmButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("");
        confirmButton.setBorderPainted(false);
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        detailsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Started", "Not Finished", "Finished", "100% Complete" }));
        detailsCombo.setEnabled(false);

        statusPane.setBackground(new java.awt.Color(44, 47, 51));
        statusPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        haveRadio.setBackground(new java.awt.Color(153, 153, 153));
        statusButtons.add(haveRadio);
        haveRadio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        haveRadio.setForeground(new java.awt.Color(153, 153, 153));
        haveRadio.setText("Have");
        haveRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                haveRadioStateChanged(evt);
            }
        });

        wantRadio.setBackground(new java.awt.Color(153, 153, 153));
        statusButtons.add(wantRadio);
        wantRadio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        wantRadio.setForeground(new java.awt.Color(153, 153, 153));
        wantRadio.setText("Want");

        javax.swing.GroupLayout statusPaneLayout = new javax.swing.GroupLayout(statusPane);
        statusPane.setLayout(statusPaneLayout);
        statusPaneLayout.setHorizontalGroup(
            statusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wantRadio)
            .addComponent(haveRadio)
        );
        statusPaneLayout.setVerticalGroup(
            statusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPaneLayout.createSequentialGroup()
                .addComponent(wantRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(haveRadio)
                .addGap(25, 25, 25))
        );

        detailsLabel.setForeground(new java.awt.Color(153, 153, 153));
        detailsLabel.setText("Details:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(detailsLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(detailsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPane, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(detailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(closeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //close frame
    private void haveRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_haveRadioStateChanged
        detailsCombo.setEnabled(haveRadio.isSelected());
    }//GEN-LAST:event_haveRadioStateChanged

    //when cofirm selected returns game to main menu with new state and own
    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        // TODO add your handling code here:
        if (haveRadio.isSelected()) {
            change.setOwn(true);
            switch (detailsCombo.getSelectedIndex()) {
                case 0:
                    change.setStatus("Not Started");
                    break;
                
                case 1:
                    change.setStatus("Started");                    
                    break;
                
                case 2:
                    change.setStatus("Finished");                    
                    break;
                
                case 3:
                    change.setStatus("100% Complete");                    
                    break;
            }
        } else {
            change.setOwn(false);
            change.setStatus(null);
        }
        parent.addGame(change);
        parent.setEnabled(true);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        
    }//GEN-LAST:event_confirmButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        parent.setEnabled(true);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> detailsCombo;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JRadioButton haveRadio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup statusButtons;
    private javax.swing.JPanel statusPane;
    private javax.swing.JRadioButton wantRadio;
    // End of variables declaration//GEN-END:variables
}
